global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway-app"
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:2222" ]
      #- targets: [ "host.docker.internal:30222" ] Use this when gateway-app run using k8s.
        labels:
          app: gateway

  - job_name: "simulator-app"
    metrics_path: /metrics
    static_configs:
      - targets: [ "host.docker.internal:3333" ]
        labels:
          app: simulator
